from enum import Enum

class Stadiums(Enum):
    FUTSAL_X2 = "Futsal x2"
    FUTSAL_X3 = "Futsal x3"
    FUTSAL_X4 = "Futsal x4"
    FUTSAL_X5 = "Futsal x5"
    FUTSAL_X5_CESPED = "Futsal x5 cesped"
    FUTSAL_X7 = "Futsal x7"
    REAL_SOCCER = "Real Soccer"
    REAL_SOCCER_EVO = "Real Soccer Evo"
    REAL_FUTSAL = "Real Futsal"
    ENTRENAMIENTO = "Entrenamiento"
    BASQUET = "Basquet"
    MINI_RS = "Mini RS"
    CAMPEONES = "Campeones"
    PREMIOS = "Premios"
    BIG = "Big"
    VOLEY_2D = "Voley 2d"
    VOLEY_3D = "Voley 3d"
    ESCUELA = "Escuela"
    SKATE = "Skate"
    HANDBALL = "Handball"
    TENIS_LADRILLO = "Tenis Ladrillo"
    TENIS_PASTO = "Tenis Pasto"
    TENIS_CEMENTO = "Tenis Cemento"
    RS_REALISTA = "RS Realista"
    RS_OVEJA = "RS Oveja"
    PENALES_RED = "Penales Red"
    PENALES_BLUE = "Penales Blue"
    TWO_MAN = "2 Man"
    THREE_MAN = "3 Man"
    FOUR_MAN = "4 Man"
    FIVE_MAN = "5 Man"
    SIX_MAN = "6 Man"
    SEVEN_MAN = "7 Man"
    EIGHT_MAN = "8 Man"